# Master extraction schema — the EXACT JSON structure the LLM fills in.
# Each document adds its data to this template progressively.

MASTER_SCHEMA = {
    # ─── GST Data (from GSTR-1 / GSTR-3B) ───
    "gstin": None,
    "legal_name": None,
    "trade_name": None,
    "gst_filing_status": None,
    "gst_filing_period": None,
    "gst_filing_date": None,
    "total_taxable_value_domestic": None,
    "total_taxable_value_exports": None,
    "total_igst": None,
    "total_cgst": None,
    "total_sgst": None,
    "total_tax_collected": None,
    "num_b2b_invoices": None,
    "num_amendments": None,
    "itc_available_total": None,
    "itc_claimed_total": None,
    "b2b_invoices": [],
    "export_invoices": [],

    # ─── ITR Data (from ITR-3 / ITR-6) ───
    "pan_number": None,
    "assessee_name": None,
    "assessment_year": None,
    "financial_year": None,
    "itr_filing_date": None,
    "nature_of_business": None,
    "gross_receipts": None,
    "total_expenses": None,
    "net_profit_from_business": None,
    "other_income": None,
    "gross_total_income": None,
    "total_deductions_vi_a": None,
    "taxable_income": None,
    "total_tax_payable": None,
    "tax_paid_advance_tds": None,
    "depreciation": None,
    "interest_paid": None,
    "house_property_loss": None,
    "section_80c_deduction": None,
    "section_80d_deduction": None,
    "donations_80g": None,

    # ─── Financial Statements / Annual Report Data ───
    "company_name": None,
    "cin": None,
    "fs_financial_year": None,
    "industry": None,
    "revenue_from_operations": None,
    "fs_other_income": None,
    "total_revenue": None,
    "fs_total_expenses": None,
    "ebitda": None,
    "fs_depreciation": None,
    "profit_before_tax": None,
    "tax_expense": None,
    "profit_after_tax": None,
    "total_assets": None,
    "total_liabilities": None,
    "net_worth": None,
    "total_debt": None,
    "current_assets": None,
    "current_liabilities": None,
    "cash_and_equivalents": None,
    "trade_receivables": None,
    "trade_payables": None,
    "inventory": None,
    "share_capital": None,
    "reserves_and_surplus": None,
    "director_remuneration": None,
    "loans_from_directors": None,
    "num_employees": None,
    "auditor_name": None,
    "audit_opinion": None,
    "dividend_declared": None,
    "related_party_transactions_total": None,

    # ─── Bank Statement Data ───
    "bank_name": None,
    "bank_branch": None,
    "account_number": None,
    "account_type": None,
    "statement_from_date": None,
    "statement_to_date": None,
    "opening_balance": None,
    "closing_balance": None,
    "total_credits": None,
    "total_debits": None,
    "num_credit_transactions": None,
    "num_debit_transactions": None,
    "avg_monthly_balance": None,
    "min_balance": None,
    "max_balance": None,
    "od_cc_limit": None,
    "num_cheque_bounces": None,
    "num_emi_payments": None,
    "total_emi_amount": None,
    "num_gst_payments": None,
    "total_gst_paid": None,
    "salary_credits_total": None,
    "large_cash_deposits": [],
    "large_cash_withdrawals": [],
}
